# Generated by Django 5.2.4 on 2026-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('span_id', models.CharField(max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('correlation_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(db_index=True, max_length=128)),
                ('video_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('analysis_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('frame_index', models.IntegerField(blank=True, null=True)),
                ('segment_start', models.FloatField(blank=True, null=True)),
                ('segment_end', models.FloatField(blank=True, null=True)),
                ('commentary', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trace_id', 'frame_index'], name='observabili_trace_i_ac5bc1_idx'), models.Index(fields=['video_id', 'frame_index'], name='observabili_video_i_163a92_idx'), models.Index(fields=['source', 'timestamp'], name='observabili_source_54d8a8_idx')],
            },
        ),
    ]
